apiVersion: v1
kind: Service
metadata:
  # This name is important , it's the name of our service
  # and it should be the same name mentioned in application.properties
  name: vprocache01
spec:
  type: ClusterIP
  ports:
  - targetPort: vpromc-port
    port: 11211
    protocol: TCP
  selector:
    app: vpromc
