apiVersion: v1
kind: Service
metadata:
  # This name is important , it's the name of our service
  # and it should be the same name mentioned in application.properties
  name: vpromq01
spec:
  type: ClusterIP
  ports:
  - targetPort: vpromq01-port
    port: 15672
    protocol: TCP
  selector:
    app: vpromq01
