apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
spec:
  selector:
    matchLabels:
      app: vproapp
  replicas: 1
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: {{ .Values.appimage }}
        ports:
        - name: vproapp-port
          containerPort: 8080
      initContainers: # these containers will be dead after they finish.
        # We want DB container to be created first then it should create this pod
        # so the app container will be halted as long as db service is not ready
      - name: init-mydb
        image: busybox:1.28
        # this command will check the DB service , we're running a bash until loop
        # every 2 secs it will run nslookup vprodb until returns true 
        # NOTE : nslookup is used on the SERVICE name not the POD name
        command: ['sh', '-c', 'until nslookup vprodb; do echo waiting for my db; sleep 2; done;']
      - name: init-memcache
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup vprocache01; do echo waiting for my mc; sleep 2; done;']

